(package-install 'which-key)
(package-install 'company)
(package-install 'company)
(package-install 'counsel-projectile)
(package-install 'smex)
(package-install 'magit)
		  (package-install 'helm)
		  (package-install 'projectile )
		  (package-install 'helm-projectile)
